import phone from './213031-3.jpg';
import dongho from './se-40mm-vien-nhom-day-cao-su-xanh-den-thumb-1-600x600.jpg';
import taynghe from './bluetooth-true-wireless-ava-ds204a-wb-trang-thumb-1-600x600.jpg';
import iconred from './icon5-50x50.png';
import iconyellow from './icon1-50x50.png';
import chuot from './chuot-gaming-asus-tuf-m3-den01-600x600.jpg';
import laptop from './msi-gaming-gf63-thin-10sc-i7-10750h-8gb-512gb-600x600.jpg';
import taynghe2 from './tai-nghe-bluetooth-true-wireless-mozard-ts13-thumb-2-600x600.jpg';
import iconintel from './Label-Intel-Gen10.png';
import phone2 from './realme-c21-y-blue-600x600.jpg';
import laptop2 from './acer-aspire-a514-54-511g-i5-nxa28sv009-thumb-600x600.jpg';
import wifi from './bo-phat-song-wifi-router-chuan-wifi-6-asus-ax1800hp-den-thumb-600x600.jpg';
import iconintel2 from './11th-gen-core-i5-processors-badge-rwd.png.rendition.intel.web.550.550.jpg';
import phone3 from './Samsung-Galaxy-A53-xanh-thumb-600x600.jpg';
import loa from './bluetooth-mozard-s21-ava-600x600.jpg';
import sac from './pin-polymer-10000mah-type-c-ava-ds2107-thumb-600x600.jpg';

export const ProductGoiYHomNay = [
    // {
    //   id: '',
    //   tragop: '',
    //   image: '',
    //   new: '',
    //   baohanh: '',
    //   title: '',
    //   preorder: '',
    //   result: {
    //     class: '',
    //     image: '',
    //     title: '',
    //   },
    //   text_online: '',
    //   price: '',
    //   discount: '',
    //   gift: '',
    //   vote: {
    //     vote: '',
    //     numbervote: '',
    //   }
    // },
    {
        id: 0,
        tragop: 'Trả góp 0%',
        image: phone,
        title: 'iPhone 12 64GB',
        result: {
            class: 'red',
            image: iconred,
            title: 'FLASHSALE GIẢM SỐC',
        },
        price: '16.490.000',
        discount: '-17%',
        vote: {
            vote: '4.0',
            numbervote: '(237)',
        },
    },
    {
        id: 0,
        tragop: ' ',
        image: taynghe,
        title: 'Tai nghe Bluetooth True Wireless AVA+ DS204A-WB',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '455.00',
        discount: '-30%',
        vote: {
            vote: '3.4',
            numbervote: '(214)',
        },
    },
    {
        id: 0,
        tragop: ' ',
        image: dongho,
        title: 'Apple Watch SE 40mm viền nhôm dây silicone',
        result: {
            class: 'yellow-red',
            image: iconyellow,
            title: 'SALE GIỮA THÁNG',
        },
        price: '6.990.000',
        discount: '-22%',
        vote: {
            vote: '4.5',
            numbervote: '(68)',
        },
    },
    {
        id: 0,
        tragop: 'Trả góp 0%',
        image: phone,
        title: 'iPhone 12 64GB',
        result: {
            class: 'red',
            image: iconred,
            title: 'FLASHSALE GIẢM SỐC',
        },
        price: '16.490.000',
        discount: '-17%',
        vote: {
            vote: '4.0',
            numbervote: '(237)',
        },
    },
    {
        id: 0,
        tragop: ' ',
        image: taynghe,
        title: 'Tai nghe Bluetooth True Wireless AVA+ DS204A-WB',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '455.00',
        discount: '-30%',
        vote: {
            vote: '3.4',
            numbervote: '(214)',
        },
    },
    {
        id: 0,
        tragop: ' ',
        image: dongho,
        title: 'Apple Watch SE 40mm viền nhôm dây silicone',
        result: {
            class: 'yellow-red',
            image: iconyellow,
            title: 'SALE GIỮA THÁNG',
        },
        price: '6.990.000',
        discount: '-22%',
        vote: {
            vote: '4.5',
            numbervote: '(68)',
        },
    },
    {
        id: 0,
        tragop: 'Trả góp 0%',
        image: phone,
        title: 'iPhone 12 64GB',
        result: {
            class: 'red',
            image: iconred,
            title: 'FLASHSALE GIẢM SỐC',
        },
        price: '16.490.000',
        discount: '-17%',
        vote: {
            vote: '4.0',
            numbervote: '(237)',
        },
    },
    {
        id: 0,
        tragop: ' ',
        image: taynghe,
        title: 'Tai nghe Bluetooth True Wireless AVA+ DS204A-WB',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '455.00',
        discount: '-30%',
        vote: {
            vote: '3.4',
            numbervote: '(214)',
        },
    },
    {
        id: 0,
        tragop: ' ',
        image: dongho,
        title: 'Apple Watch SE 40mm viền nhôm dây silicone',
        result: {
            class: 'yellow-red',
            image: iconyellow,
            title: 'SALE GIỮA THÁNG',
        },
        price: '6.990.000',
        discount: '-22%',
        vote: {
            vote: '4.5',
            numbervote: '(68)',
        },
    },
    {
        id: 0,
        tragop: 'Trả góp 0%',
        image: phone,
        title: 'iPhone 12 64GB',
        result: {
            class: 'red',
            image: iconred,
            title: 'FLASHSALE GIẢM SỐC',
        },
        price: '16.490.000',
        discount: '-17%',
        vote: {
            vote: '4.0',
            numbervote: '(237)',
        },
    },
    {
        id: 0,
        tragop: ' ',
        image: taynghe,
        title: 'Tai nghe Bluetooth True Wireless AVA+ DS204A-WB',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '455.00',
        discount: '-30%',
        vote: {
            vote: '3.4',
            numbervote: '(214)',
        },
    },
    {
        id: 0,
        tragop: ' ',
        image: dongho,
        title: 'Apple Watch SE 40mm viền nhôm dây silicone',
        result: {
            class: 'yellow-red',
            image: iconyellow,
            title: 'SALE GIỮA THÁNG',
        },
        price: '6.990.000',
        discount: '-22%',
        vote: {
            vote: '4.5',
            numbervote: '(68)',
        },
    },
    {
        id: 0,
        tragop: 'Trả góp 0%',
        image: phone,
        title: 'iPhone 12 64GB',
        result: {
            class: 'red',
            image: iconred,
            title: 'FLASHSALE GIẢM SỐC',
        },
        price: '16.490.000',
        discount: '-17%',
        vote: {
            vote: '4.0',
            numbervote: '(237)',
        },
    },
    {
        id: 0,
        tragop: ' ',
        image: taynghe,
        title: 'Tai nghe Bluetooth True Wireless AVA+ DS204A-WB',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '455.00',
        discount: '-30%',
        vote: {
            vote: '3.4',
            numbervote: '(214)',
        },
    },
    {
        id: 0,
        tragop: ' ',
        image: dongho,
        title: 'Apple Watch SE 40mm viền nhôm dây silicone',
        result: {
            class: 'yellow-red',
            image: iconyellow,
            title: 'SALE GIỮA THÁNG',
        },
        price: '6.990.000',
        discount: '-22%',
        vote: {
            vote: '4.5',
            numbervote: '(68)',
        },
    },
    {
        id: 0,
        tragop: 'Trả góp 0%',
        image: phone,
        title: 'iPhone 12 64GB',
        result: {
            class: 'red',
            image: iconred,
            title: 'FLASHSALE GIẢM SỐC',
        },
        price: '16.490.000',
        discount: '-17%',
        vote: {
            vote: '4.0',
            numbervote: '(237)',
        },
    },
    {
        id: 0,
        tragop: ' ',
        image: taynghe,
        title: 'Tai nghe Bluetooth True Wireless AVA+ DS204A-WB',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '455.00',
        discount: '-30%',
        vote: {
            vote: '3.4',
            numbervote: '(214)',
        },
    },
    {
        id: 0,
        tragop: ' ',
        image: dongho,
        title: 'Apple Watch SE 40mm viền nhôm dây silicone',
        result: {
            class: 'yellow-red',
            image: iconyellow,
            title: 'SALE GIỮA THÁNG',
        },
        price: '6.990.000',
        discount: '-22%',
        vote: {
            vote: '4.5',
            numbervote: '(68)',
        },
    },
    {
        id: 0,
        tragop: 'Trả góp 0%',
        image: phone,
        title: 'iPhone 12 64GB',
        result: {
            class: 'red',
            image: iconred,
            title: 'FLASHSALE GIẢM SỐC',
        },
        price: '16.490.000',
        discount: '-17%',
        vote: {
            vote: '4.0',
            numbervote: '(237)',
        },
    },
    {
        id: 0,
        tragop: ' ',
        image: taynghe,
        title: 'Tai nghe Bluetooth True Wireless AVA+ DS204A-WB',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '455.00',
        discount: '-30%',
        vote: {
            vote: '3.4',
            numbervote: '(214)',
        },
    },

    {
        id: 1,
        tragop: 'Trả góp 0%',
        image: laptop,
        baohanh: iconintel,
        title: 'MSI Gaming GF63 Thin 10SC i7 10750H (813VN)',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '17.790.000',
        discount: '-19%',
        gift: 'Quà 690.000₫',
        vote: {
            vote: '4.8',
            numbervote: '(8)',
        },
    },
    {
        id: 1,
        tragop: ' ',
        image: taynghe2,
        title: 'Tai nghe Bluetooth True Wireless Mozard TS13',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '355.000',
        discount: '-45%',
        vote: {
            vote: '2.9',
            numbervote: '(462)',
        },
    },
    {
        id: 1,
        tragop: ' ',
        image: chuot,
        title: 'Chuột Có Dây Gaming Asus TUF M3',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '440.000',
        discount: '-20%',
        vote: {
            vote: '4.6',
            numbervote: '(33)',
        },
    },
    {
        id: 1,
        tragop: 'Trả góp 0%',
        image: laptop,
        baohanh: iconintel,
        title: 'MSI Gaming GF63 Thin 10SC i7 10750H (813VN)',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '17.790.000',
        discount: '-19%',
        gift: 'Quà 690.000₫',
        vote: {
            vote: '4.8',
            numbervote: '(8)',
        },
    },
    {
        id: 1,
        tragop: ' ',
        image: taynghe2,
        title: 'Tai nghe Bluetooth True Wireless Mozard TS13',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '355.000',
        discount: '-45%',
        vote: {
            vote: '2.9',
            numbervote: '(462)',
        },
    },
    {
        id: 1,
        tragop: ' ',
        image: chuot,
        title: 'Chuột Có Dây Gaming Asus TUF M3',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '440.000',
        discount: '-20%',
        vote: {
            vote: '4.6',
            numbervote: '(33)',
        },
    },
    {
        id: 1,
        tragop: 'Trả góp 0%',
        image: laptop,
        baohanh: iconintel,
        title: 'MSI Gaming GF63 Thin 10SC i7 10750H (813VN)',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '17.790.000',
        discount: '-19%',
        gift: 'Quà 690.000₫',
        vote: {
            vote: '4.8',
            numbervote: '(8)',
        },
    },
    {
        id: 1,
        tragop: ' ',
        image: taynghe2,
        title: 'Tai nghe Bluetooth True Wireless Mozard TS13',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '355.000',
        discount: '-45%',
        vote: {
            vote: '2.9',
            numbervote: '(462)',
        },
    },
    {
        id: 1,
        tragop: ' ',
        image: chuot,
        title: 'Chuột Có Dây Gaming Asus TUF M3',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '440.000',
        discount: '-20%',
        vote: {
            vote: '4.6',
            numbervote: '(33)',
        },
    },
    {
        id: 1,
        tragop: 'Trả góp 0%',
        image: laptop,
        baohanh: iconintel,
        title: 'MSI Gaming GF63 Thin 10SC i7 10750H (813VN)',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '17.790.000',
        discount: '-19%',
        gift: 'Quà 690.000₫',
        vote: {
            vote: '4.8',
            numbervote: '(8)',
        },
    },
    {
        id: 1,
        tragop: ' ',
        image: taynghe2,
        title: 'Tai nghe Bluetooth True Wireless Mozard TS13',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '355.000',
        discount: '-45%',
        vote: {
            vote: '2.9',
            numbervote: '(462)',
        },
    },
    {
        id: 1,
        tragop: ' ',
        image: chuot,
        title: 'Chuột Có Dây Gaming Asus TUF M3',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '440.000',
        discount: '-20%',
        vote: {
            vote: '4.6',
            numbervote: '(33)',
        },
    },
    {
        id: 1,
        tragop: 'Trả góp 0%',
        image: laptop,
        baohanh: iconintel,
        title: 'MSI Gaming GF63 Thin 10SC i7 10750H (813VN)',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '17.790.000',
        discount: '-19%',
        gift: 'Quà 690.000₫',
        vote: {
            vote: '4.8',
            numbervote: '(8)',
        },
    },
    {
        id: 1,
        tragop: ' ',
        image: taynghe2,
        title: 'Tai nghe Bluetooth True Wireless Mozard TS13',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '355.000',
        discount: '-45%',
        vote: {
            vote: '2.9',
            numbervote: '(462)',
        },
    },
    {
        id: 1,
        tragop: ' ',
        image: chuot,
        title: 'Chuột Có Dây Gaming Asus TUF M3',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '440.000',
        discount: '-20%',
        vote: {
            vote: '4.6',
            numbervote: '(33)',
        },
    },
    {
        id: 1,
        tragop: 'Trả góp 0%',
        image: laptop,
        baohanh: iconintel,
        title: 'MSI Gaming GF63 Thin 10SC i7 10750H (813VN)',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '17.790.000',
        discount: '-19%',
        gift: 'Quà 690.000₫',
        vote: {
            vote: '4.8',
            numbervote: '(8)',
        },
    },
    {
        id: 1,
        tragop: ' ',
        image: taynghe2,
        title: 'Tai nghe Bluetooth True Wireless Mozard TS13',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '355.000',
        discount: '-45%',
        vote: {
            vote: '2.9',
            numbervote: '(462)',
        },
    },
    {
        id: 1,
        tragop: ' ',
        image: chuot,
        title: 'Chuột Có Dây Gaming Asus TUF M3',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '440.000',
        discount: '-20%',
        vote: {
            vote: '4.6',
            numbervote: '(33)',
        },
    },
    {
        id: 1,
        tragop: 'Trả góp 0%',
        image: laptop,
        baohanh: iconintel,
        title: 'MSI Gaming GF63 Thin 10SC i7 10750H (813VN)',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '17.790.000',
        discount: '-19%',
        gift: 'Quà 690.000₫',
        vote: {
            vote: '4.8',
            numbervote: '(8)',
        },
    },
    {
        id: 1,
        tragop: ' ',
        image: taynghe2,
        title: 'Tai nghe Bluetooth True Wireless Mozard TS13',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '355.000',
        discount: '-45%',
        vote: {
            vote: '2.9',
            numbervote: '(462)',
        },
    },

    {
        id: 2,
        tragop: 'Trả góp 0%',
        image: phone2,
        title: 'Realme C21-Y 4GB',
        price: '3.290.000',
        discount: '-23%',
        vote: {
            vote: '3.7',
            numbervote: '(17)',
        },
    },
    {
        id: 2,
        tragop: 'Trả góp 0%',
        image: laptop2,
        baohanh: iconintel2,
        title: 'Acer Aspire A514 54 511G i5 1135G7 (NX.A28SV.009)',
        result: {
            class: 'red',
            image: iconred,
            title: 'GIÁ SỐC CUỐI TUẦN',
        },
        text_online: 'Online giá rẻ',
        price: '15.790.000',
        discount: '-21%',
        gift: 'Quà 300.000₫',
        vote: {
            vote: '3.8',
            numbervote: '(8)',
        },
    },
    {
        id: 2,
        tragop: ' ',
        image: wifi,
        title: 'Router Wifi Chuẩn Wifi 6 Asus AX1800HP Đen',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '1.510.000',
        discount: '-20%',
        gift: '',
        vote: {
            vote: '',
            numbervote: '',
        },
    },
    {
        id: 2,
        tragop: 'Trả góp 0%',
        image: phone2,
        title: 'Realme C21-Y 4GB',
        price: '3.290.000',
        discount: '-23%',
        vote: {
            vote: '3.7',
            numbervote: '(17)',
        },
    },
    {
        id: 2,
        tragop: 'Trả góp 0%',
        image: laptop2,
        baohanh: iconintel2,
        title: 'Acer Aspire A514 54 511G i5 1135G7 (NX.A28SV.009)',
        result: {
            class: 'red',
            image: iconred,
            title: 'GIÁ SỐC CUỐI TUẦN',
        },
        text_online: 'Online giá rẻ',
        price: '15.790.000',
        discount: '-21%',
        gift: 'Quà 300.000₫',
        vote: {
            vote: '3.8',
            numbervote: '(8)',
        },
    },
    {
        id: 2,
        tragop: ' ',
        image: wifi,
        title: 'Router Wifi Chuẩn Wifi 6 Asus AX1800HP Đen',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '1.510.000',
        discount: '-20%',
        gift: '',
        vote: {
            vote: '',
            numbervote: '',
        },
    },
    {
        id: 2,
        tragop: 'Trả góp 0%',
        image: phone2,
        title: 'Realme C21-Y 4GB',
        price: '3.290.000',
        discount: '-23%',
        vote: {
            vote: '3.7',
            numbervote: '(17)',
        },
    },
    {
        id: 2,
        tragop: 'Trả góp 0%',
        image: laptop2,
        baohanh: iconintel2,
        title: 'Acer Aspire A514 54 511G i5 1135G7 (NX.A28SV.009)',
        result: {
            class: 'red',
            image: iconred,
            title: 'GIÁ SỐC CUỐI TUẦN',
        },
        text_online: 'Online giá rẻ',
        price: '15.790.000',
        discount: '-21%',
        gift: 'Quà 300.000₫',
        vote: {
            vote: '3.8',
            numbervote: '(8)',
        },
    },
    {
        id: 2,
        tragop: ' ',
        image: wifi,
        title: 'Router Wifi Chuẩn Wifi 6 Asus AX1800HP Đen',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '1.510.000',
        discount: '-20%',
        gift: '',
        vote: {
            vote: '',
            numbervote: '',
        },
    },
    {
        id: 2,
        tragop: 'Trả góp 0%',
        image: phone2,
        title: 'Realme C21-Y 4GB',
        price: '3.290.000',
        discount: '-23%',
        vote: {
            vote: '3.7',
            numbervote: '(17)',
        },
    },
    {
        id: 2,
        tragop: 'Trả góp 0%',
        image: laptop2,
        baohanh: iconintel2,
        title: 'Acer Aspire A514 54 511G i5 1135G7 (NX.A28SV.009)',
        result: {
            class: 'red',
            image: iconred,
            title: 'GIÁ SỐC CUỐI TUẦN',
        },
        text_online: 'Online giá rẻ',
        price: '15.790.000',
        discount: '-21%',
        gift: 'Quà 300.000₫',
        vote: {
            vote: '3.8',
            numbervote: '(8)',
        },
    },
    {
        id: 2,
        tragop: ' ',
        image: wifi,
        title: 'Router Wifi Chuẩn Wifi 6 Asus AX1800HP Đen',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '1.510.000',
        discount: '-20%',
        gift: '',
        vote: {
            vote: '',
            numbervote: '',
        },
    },
    {
        id: 2,
        tragop: 'Trả góp 0%',
        image: phone2,
        title: 'Realme C21-Y 4GB',
        price: '3.290.000',
        discount: '-23%',
        vote: {
            vote: '3.7',
            numbervote: '(17)',
        },
    },
    {
        id: 2,
        tragop: 'Trả góp 0%',
        image: laptop2,
        baohanh: iconintel2,
        title: 'Acer Aspire A514 54 511G i5 1135G7 (NX.A28SV.009)',
        result: {
            class: 'red',
            image: iconred,
            title: 'GIÁ SỐC CUỐI TUẦN',
        },
        text_online: 'Online giá rẻ',
        price: '15.790.000',
        discount: '-21%',
        gift: 'Quà 300.000₫',
        vote: {
            vote: '3.8',
            numbervote: '(8)',
        },
    },
    {
        id: 2,
        tragop: ' ',
        image: wifi,
        title: 'Router Wifi Chuẩn Wifi 6 Asus AX1800HP Đen',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '1.510.000',
        discount: '-20%',
        gift: '',
        vote: {
            vote: '',
            numbervote: '',
        },
    },
    {
        id: 2,
        tragop: 'Trả góp 0%',
        image: phone2,
        title: 'Realme C21-Y 4GB',
        price: '3.290.000',
        discount: '-23%',
        vote: {
            vote: '3.7',
            numbervote: '(17)',
        },
    },
    {
        id: 2,
        tragop: 'Trả góp 0%',
        image: laptop2,
        baohanh: iconintel2,
        title: 'Acer Aspire A514 54 511G i5 1135G7 (NX.A28SV.009)',
        result: {
            class: 'red',
            image: iconred,
            title: 'GIÁ SỐC CUỐI TUẦN',
        },
        text_online: 'Online giá rẻ',
        price: '15.790.000',
        discount: '-21%',
        gift: 'Quà 300.000₫',
        vote: {
            vote: '3.8',
            numbervote: '(8)',
        },
    },
    {
        id: 2,
        tragop: ' ',
        image: wifi,
        title: 'Router Wifi Chuẩn Wifi 6 Asus AX1800HP Đen',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '1.510.000',
        discount: '-20%',
        gift: '',
        vote: {
            vote: '',
            numbervote: '',
        },
    },
    {
        id: 2,
        tragop: 'Trả góp 0%',
        image: phone2,
        title: 'Realme C21-Y 4GB',
        price: '3.290.000',
        discount: '-23%',
        vote: {
            vote: '3.7',
            numbervote: '(17)',
        },
    },
    {
        id: 2,
        tragop: 'Trả góp 0%',
        image: laptop2,
        baohanh: iconintel2,
        title: 'Acer Aspire A514 54 511G i5 1135G7 (NX.A28SV.009)',
        result: {
            class: 'red',
            image: iconred,
            title: 'GIÁ SỐC CUỐI TUẦN',
        },
        text_online: 'Online giá rẻ',
        price: '15.790.000',
        discount: '-21%',
        gift: 'Quà 300.000₫',
        vote: {
            vote: '3.8',
            numbervote: '(8)',
        },
    },

    {
        id: 3,
        tragop: 'Trả góp 0%',
        image: phone3,
        title: 'Samsung Galaxy A53 5G',
        price: '9.990.000',
        vote: {
            vote: '3.4',
            numbervote: '(198)',
        },
    },
    {
        id: 3,
        tragop: ' ',
        image: loa,
        title: 'Loa Bluetooth Mozard S21',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '290.000',
        discount: '-47%',
        vote: {
            vote: '4.0',
            numbervote: '(26)',
        },
    },
    {
        id: 3,
        tragop: ' ',
        image: sac,
        title: 'AVA+ DS2107',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '300.000',
        discount: '-45%',
        vote: {
            vote: '3.6',
            numbervote: '(20)',
        },
    },
    {
        id: 3,
        tragop: 'Trả góp 0%',
        image: phone3,
        title: 'Samsung Galaxy A53 5G',
        price: '9.990.000',
        vote: {
            vote: '3.4',
            numbervote: '(198)',
        },
    },
    {
        id: 3,
        tragop: ' ',
        image: loa,
        title: 'Loa Bluetooth Mozard S21',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '290.000',
        discount: '-47%',
        vote: {
            vote: '4.0',
            numbervote: '(26)',
        },
    },
    {
        id: 3,
        tragop: ' ',
        image: sac,
        title: 'AVA+ DS2107',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '300.000',
        discount: '-45%',
        vote: {
            vote: '3.6',
            numbervote: '(20)',
        },
    },
    {
        id: 3,
        tragop: 'Trả góp 0%',
        image: phone3,
        title: 'Samsung Galaxy A53 5G',
        price: '9.990.000',
        vote: {
            vote: '3.4',
            numbervote: '(198)',
        },
    },
    {
        id: 3,
        tragop: ' ',
        image: loa,
        title: 'Loa Bluetooth Mozard S21',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '290.000',
        discount: '-47%',
        vote: {
            vote: '4.0',
            numbervote: '(26)',
        },
    },
    {
        id: 3,
        tragop: ' ',
        image: sac,
        title: 'AVA+ DS2107',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '300.000',
        discount: '-45%',
        vote: {
            vote: '3.6',
            numbervote: '(20)',
        },
    },
    {
        id: 3,
        tragop: 'Trả góp 0%',
        image: phone3,
        title: 'Samsung Galaxy A53 5G',
        price: '9.990.000',
        vote: {
            vote: '3.4',
            numbervote: '(198)',
        },
    },
    {
        id: 3,
        tragop: ' ',
        image: loa,
        title: 'Loa Bluetooth Mozard S21',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '290.000',
        discount: '-47%',
        vote: {
            vote: '4.0',
            numbervote: '(26)',
        },
    },
    {
        id: 3,
        tragop: ' ',
        image: sac,
        title: 'AVA+ DS2107',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '300.000',
        discount: '-45%',
        vote: {
            vote: '3.6',
            numbervote: '(20)',
        },
    },
    {
        id: 3,
        tragop: 'Trả góp 0%',
        image: phone3,
        title: 'Samsung Galaxy A53 5G',
        price: '9.990.000',
        vote: {
            vote: '3.4',
            numbervote: '(198)',
        },
    },
    {
        id: 3,
        tragop: ' ',
        image: loa,
        title: 'Loa Bluetooth Mozard S21',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '290.000',
        discount: '-47%',
        vote: {
            vote: '4.0',
            numbervote: '(26)',
        },
    },
    {
        id: 3,
        tragop: ' ',
        image: sac,
        title: 'AVA+ DS2107',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '300.000',
        discount: '-45%',
        vote: {
            vote: '3.6',
            numbervote: '(20)',
        },
    },
    {
        id: 3,
        tragop: 'Trả góp 0%',
        image: phone3,
        title: 'Samsung Galaxy A53 5G',
        price: '9.990.000',
        vote: {
            vote: '3.4',
            numbervote: '(198)',
        },
    },
    {
        id: 3,
        tragop: ' ',
        image: loa,
        title: 'Loa Bluetooth Mozard S21',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '290.000',
        discount: '-47%',
        vote: {
            vote: '4.0',
            numbervote: '(26)',
        },
    },
    {
        id: 3,
        tragop: ' ',
        image: sac,
        title: 'AVA+ DS2107',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '300.000',
        discount: '-45%',
        vote: {
            vote: '3.6',
            numbervote: '(20)',
        },
    },
    {
        id: 3,
        tragop: 'Trả góp 0%',
        image: phone3,
        title: 'Samsung Galaxy A53 5G',
        price: '9.990.000',
        vote: {
            vote: '3.4',
            numbervote: '(198)',
        },
    },
    {
        id: 3,
        tragop: ' ',
        image: loa,
        title: 'Loa Bluetooth Mozard S21',
        result: {
            class: 'red',
            image: iconyellow,
            title: 'GIẢM SỐC',
        },
        price: '290.000',
        discount: '-47%',
        vote: {
            vote: '4.0',
            numbervote: '(26)',
        },
    },
];
