import SamSung1 from './samsung-galaxy-z-fold4-kem-256gb-600x600.jpg';
import MoiRaMat from './label-moi-ra-mat-fnal.png';
import Oppo1 from './oppo-reno8z-5g-den-thumb-600x600.jpg';
import iPhone1 from './iphone-13-pro-max-sierra-blue-600x600.jpg';
import VNPAY from './icon6-50x50.png';
import SamSung2 from './samsung-galaxy-a33-5g-xanh-thumb-600x600.jpg';
import DocQuyen from './Label_01-05.png';
import Xiaomi1 from './xiaomi-poco-c40-thumb-vang-600x600.jpg';
import BaoHanh from './Label_01-01.png';
import Laptop1 from './lenovo-ideapad-3-15iml05-i3-81wb01dyvn-(6).jpg';
import GiaSoc from './icon5-50x50.png';

export const ImagesDealNgonMoiNgay = [
    // {
    //   tragop: '',
    //   image: '',
    //   new: '',
    //   baohanh: '',
    //   title: '',
    //   preorder: '',
    //   result: {
    //     class: '',
    //     image: '',
    //     title: '',
    //   },
    //   text_online: '',
    //   price: '',
    //   discount: '',
    //   gift: '',
    //   vote: {
    //     vote: '',
    //     numbervote: '',
    //   }
    // },
    {
        tragop: ' ',
        image: SamSung1,
        new: MoiRaMat,
        title: 'Samsung Galaxy Z Fold4 256GB',
        text_online: 'Hàng sắp về',
        price: '40.990.000',
    },
    {
        tragop: ' ',
        image: Oppo1,
        new: MoiRaMat,
        title: 'OPPO Reno8 Z 5G',
        preorder: 'Đặt trước đến 26/08',
        text_online: 'Hàng sắp về',
        price: '10.490.000',
        gift: 'Bộ quà đến 1.99 Triệu (Massage Mắt Olike + Tai nghe OPPO Enco Buds) + Trả góp 0%',
    },
    {
        tragop: ' ',
        image: iPhone1,
        title: 'iPhone 13 Pro Max 128GB',
        result: {
            class: 'blue',
            image: VNPAY,
            title: 'VNPAY GIẢM 500k',
        },
        text_online: 'Online giá rẻ',
        price: '28.790.000',
        discount: '-15%',
        vote: {
            vote: '4.6',
            numbervote: '(564)',
        },
    },
    {
        tragop: 'Trả góp 0%',
        image: SamSung2,
        title: 'Samsung Galaxy A33 5G',
        price: '6.890.000',
        discount: '-18%',
        vote: {
            vote: '3.5',
            numbervote: '(80)',
        },
    },
    {
        tragop: 'Trả gớp 0%',
        image: Xiaomi1,
        new: DocQuyen,
        title: 'POCO C40',
        price: '2.990.000',
        discount: '-14%',
        vote: {
            vote: '4.1',
            numbervote: '(87)',
        },
    },
    {
        tragop: 'Trả góp 0%',
        image: Laptop1,
        baohanh: BaoHanh,
        title: 'Lenovo IdeaPad 3 15IML05 i3 10110U (81WB01DYVN)',
        result: {
            class: 'red',
            image: GiaSoc,
            title: 'Giá Sốc Cuối Tuần',
        },
        text_online: 'Online giá rẻ',
        price: '9.090.000',
        discount: '-27%',
        gift: 'Quà 300.000₫',
        vote: {
            vote: '4.1',
            numbervote: '(17)',
        },
    },
    {
        tragop: ' ',
        image: SamSung1,
        new: MoiRaMat,
        title: 'Samsung Galaxy Z Fold4 256GB',
        text_online: 'Hàng sắp về',
        price: '40.990.000',
    },
    {
        tragop: ' ',
        image: Oppo1,
        new: MoiRaMat,
        title: 'OPPO Reno8 Z 5G',
        preorder: 'Đặt trước đến 26/08',
        text_online: 'Hàng sắp về',
        price: '10.490.000',
        gift: 'Bộ quà đến 1.99 Triệu (Massage Mắt Olike + Tai nghe OPPO Enco Buds) + Trả góp 0%',
    },
    {
        tragop: ' ',
        image: iPhone1,
        title: 'iPhone 13 Pro Max 128GB',
        result: {
            class: 'blue',
            image: VNPAY,
            title: 'VNPAY GIẢM 500k',
        },
        text_online: 'Online giá rẻ',
        price: '28.790.000',
        discount: '-15%',
        vote: {
            vote: '4.6',
            numbervote: '(564)',
        },
    },
    {
        tragop: 'Trả góp 0%',
        image: SamSung2,
        title: 'Samsung Galaxy A33 5G',
        price: '6.890.000',
        discount: '-18%',
        vote: {
            vote: '3.5',
            numbervote: '(80)',
        },
    },
    {
        tragop: 'Trả gớp 0%',
        image: Xiaomi1,
        new: DocQuyen,
        title: 'POCO C40',
        price: '2.990.000',
        discount: '-14%',
        vote: {
            vote: '4.1',
            numbervote: '(87)',
        },
    },
    {
        tragop: 'Trả góp 0%',
        image: Laptop1,
        baohanh: BaoHanh,
        title: 'Lenovo IdeaPad 3 15IML05 i3 10110U (81WB01DYVN)',
        result: {
            class: 'red',
            image: GiaSoc,
            title: 'Giá Sốc Cuối Tuần',
        },
        text_online: 'Online giá rẻ',
        price: '9.090.000',
        discount: '-27%',
        gift: 'Quà 300.000₫',
        vote: {
            vote: '4.1',
            numbervote: '(17)',
        },
    },
    {
        tragop: ' ',
        image: SamSung1,
        new: MoiRaMat,
        title: 'Samsung Galaxy Z Fold4 256GB',
        text_online: 'Hàng sắp về',
        price: '40.990.000',
    },
    {
        tragop: ' ',
        image: Oppo1,
        new: MoiRaMat,
        title: 'OPPO Reno8 Z 5G',
        preorder: 'Đặt trước đến 26/08',
        text_online: 'Hàng sắp về',
        price: '10.490.000',
        gift: 'Bộ quà đến 1.99 Triệu (Massage Mắt Olike + Tai nghe OPPO Enco Buds) + Trả góp 0%',
    },
    {
        tragop: ' ',
        image: iPhone1,
        title: 'iPhone 13 Pro Max 128GB',
        result: {
            class: 'blue',
            image: VNPAY,
            title: 'VNPAY GIẢM 500k',
        },
        text_online: 'Online giá rẻ',
        price: '28.790.000',
        discount: '-15%',
        vote: {
            vote: '4.6',
            numbervote: '(564)',
        },
    },
    {
        tragop: 'Trả góp 0%',
        image: SamSung2,
        title: 'Samsung Galaxy A33 5G',
        price: '6.890.000',
        discount: '-18%',
        vote: {
            vote: '3.5',
            numbervote: '(80)',
        },
    },
    {
        tragop: 'Trả gớp 0%',
        image: Xiaomi1,
        new: DocQuyen,
        title: 'POCO C40',
        price: '2.990.000',
        discount: '-14%',
        vote: {
            vote: '4.1',
            numbervote: '(87)',
        },
    },
    {
        tragop: 'Trả góp 0%',
        image: Laptop1,
        baohanh: BaoHanh,
        title: 'Lenovo IdeaPad 3 15IML05 i3 10110U (81WB01DYVN)',
        result: {
            class: 'red',
            image: GiaSoc,
            title: 'Giá Sốc Cuối Tuần',
        },
        text_online: 'Online giá rẻ',
        price: '9.090.000',
        discount: '-27%',
        gift: 'Quà 300.000₫',
        vote: {
            vote: '4.1',
            numbervote: '(17)',
        },
    },
    {
        tragop: ' ',
        image: SamSung1,
        new: MoiRaMat,
        title: 'Samsung Galaxy Z Fold4 256GB',
        text_online: 'Hàng sắp về',
        price: '40.990.000',
    },
    {
        tragop: ' ',
        image: Oppo1,
        new: MoiRaMat,
        title: 'OPPO Reno8 Z 5G',
        preorder: 'Đặt trước đến 26/08',
        text_online: 'Hàng sắp về',
        price: '10.490.000',
        gift: 'Bộ quà đến 1.99 Triệu (Massage Mắt Olike + Tai nghe OPPO Enco Buds) + Trả góp 0%',
    },
    {
        tragop: ' ',
        image: iPhone1,
        title: 'iPhone 13 Pro Max 128GB',
        result: {
            class: 'blue',
            image: VNPAY,
            title: 'VNPAY GIẢM 500k',
        },
        text_online: 'Online giá rẻ',
        price: '28.790.000',
        discount: '-15%',
        vote: {
            vote: '4.6',
            numbervote: '(564)',
        },
    },
    {
        tragop: 'Trả góp 0%',
        image: Laptop1,
        baohanh: BaoHanh,
        title: 'Lenovo IdeaPad 3 15IML05 i3 10110U (81WB01DYVN)',
        result: {
            class: 'red',
            image: GiaSoc,
            title: 'Giá Sốc Cuối Tuần',
        },
        text_online: 'Online giá rẻ',
        price: '9.090.000',
        discount: '-27%',
        gift: 'Quà 300.000₫',
        vote: {
            vote: '4.1',
            numbervote: '(17)',
        },
    },
];
